[package]
name = "jormungandrwallet"
version = "0.2.0"
authors = ["Nicolas Di Prima <nicolas@primetype.co.uk>", "Vincent Hanquez <vincent@typed.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
crate-type = [ "staticlib", "lib" ]

[dependencies]
bip39 = { path = "../bip39" }
wallet = { path = "../wallet" }
chain-ser = { path = "../chain-deps/chain-ser" }
chain-impl-mockchain = { path = "../chain-deps/chain-impl-mockchain" }