[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = { version = "0.19.3", features = ["with-serde_json-1"] }
serde_json = "1.0.83"
serde = { version = "1.0.143", features = ["derive"] }
chain-crypto = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-core = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-ser = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
cardano-serialization-lib = "11.0.0"
hex = "0.3.2"
rust_decimal = { version = "1.26", features = ["serde", "db-postgres"] }
compare = "0.1"
