[package]
name = "chain-crypto"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent.hanquez@iohk.io>"]
license = "MIT OR Apache-2.0"
edition = "2018"
keywords = [ "Crypto", "VRF", "Ed25519", "MMM" ]

[dependencies]
bech32 = "0.6"
cryptoxide = "0.1"
curve25519-dalek = "2"
ed25519-dalek = "1.0.0-pre.3"
sha2 = "^0.8"
digest = "^0.8"
generic-array = "^0.13"
rand_core = "0.5"
rand_chacha = { version = "0.2", optional = true }
quickcheck = { version = "0.9", optional = true }
ed25519-bip32 = "0.3"
cfg-if = "0.1"
hex = "0.3.2"
typed-bytes = { path = "../typed-bytes" }

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.8"
rand_chacha = "0.2"

[features]
with-bench = [ 'curve25519-dalek/simd_backend']
property-test-api = [ "quickcheck", "rand_chacha" ]
