[package]
name = "network-core"
version = "0.1.0-dev"
description = "Network subsystem API for blockchain node"
authors = ["dev@iohk.io"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
chain-core = { path = "../chain-core" }
bytes = "0.4"
futures = "0.1"
thiserror = "1.0"
