[workspace]
members = [
    "imhamt",
    "chain-core",
    "chain-addr",
    "chain-time",
    "chain-crypto",
    "chain-storage",
    "chain-storage-sqlite",
    "chain-storage-sqlite-old",
    "chain-impl-mockchain",
    "cardano-legacy-address",
    "network-core",
    "network-grpc",
    "sparse-array",
    "typed-bytes",
]
