[package]
name = "thor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jcli = { path = "../../jcli" }
jormungandr-lib = { workspace = true }
jormungandr-automation = { path = "../jormungandr-automation" }
jortestkit = { path = "../../../jortestkit" }
chain-impl-mockchain = { workspace = true, features = [ "property-test-api" ] }
chain-addr      = { path = "../../../chain-libs/chain-addr", features = [ "property-test-api" ] }
chain-crypto    = { path = "../../../chain-libs/chain-crypto", features = [ "property-test-api" ] }
chain-core      = { path = "../../../chain-libs/chain-core" }
chain-vote      = { path = "../../../chain-libs/chain-vote" }
assert_fs = "1.0"
serde = { version = "1.0", features = ["derive"] }
cocoon =  { git = "https://github.com/dkijania/cocoon.git" }
dirs = "4.0.0"
serde_yaml = "0.8"
clap = { workspace = true }
rand = "0.8"
rand_core = "0.6"
rand_chacha = "0.3"
thiserror = "1.0"
custom_debug = "0.5"
bincode = "1.3"
hex = "0.4"
bech32 = "0.8"
time = { version = "0.3", features = ["macros"] }

[dev-dependencies]
bincode = "1.3"
