[package]
name = "vit-servicing-station-lib"
version = "0.5.0"
authors = ["danielsanchezq <daniel.sanchez@iohk.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.33"
base64 = "0.12.1"
time = { version = "0.3", features = ["parsing", "formatting"] }
diesel = { version = "1.4.5", features = ["sqlite", "r2d2"] }
diesel_migrations = "1.4.0"
dotenv = "0.15"
itertools = "0.9.0"
log = { version = "0.4.11", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.53"
strum = "0.21.0"
strum_macros = "0.21.1"
simplelog = "0.8.0"
structopt = "0.3.14"
thiserror = "1.0"
tokio = { version = "^1.0", features = ["macros", "signal", "rt", "fs", "sync"] }
tracing = "0.1"
tracing-futures = "0.2.4"
tracing-subscriber = "0.3"
warp = { version = "0.3", features = ["tls"] }
eccoxide = { git = "https://github.com/eugene-babichenko/eccoxide.git", branch = "fast-u64-scalar-mul", features = ["fast-u64-scalar-mul"], optional = true }
http-zipkin = "0.3.0"
notify = "=5.0.0-pre.11"
voting-hir = { git = "https://github.com/input-output-hk/catalyst-toolbox", branch = "catalyst-fund9", features = ["serde"] }
snapshot-service = { path = "../snapshot-service" }

# This solves building on windows when sqlite3lib is not installed or missing in the `$PATH`
# as it happens with the github actions pipeline associated to this project.
[target.'cfg(windows)'.dependencies]
libsqlite3-sys =  { version = "0.9.3", features = ["bundled"] }

[dev-dependencies]
tempfile = "3"
rand = "0.8"
jormungandr-lib = { git = "https://github.com/input-output-hk/jormungandr", branch = "catalyst-fund9" }
