{   
   "initials": [
    {
      "above_threshold": 1,
      "pin": "1234"
    }
  ], 
  "vote_start": 0,
  "vote_tally": 22,
  "tally_end": 32,
  "refresh_time": "2021-06-11T11:00:00",
  "next_vote_start_time": "2021-07-05T16:00:00",
  "proposals": 280,
  "challenges": 7,
  "slot_duration": 20,
  "slots_per_epoch": 4320,
  "voting_power": 450,
  "fund_name": "Fund4",
  "private": false,
  "fund_id": 4,
  "linear_fees": {
    "constant": 0,
    "coefficient": 0,
    "certificate": 0
  },
  "consensus_leader_ids": [
    "ed25519_pk1lv8m52aakjm2z0yqtltqxp6f9kemtcmt9ej7gn86eru7gpt8tn0q08j8lt",
    "ed25519_pk1qvq6prs87lmg6aeurdhq93fhtrx034yzc3jgj6lc3xc3a8lff98qtgw4dw",
    "ed25519_pk1g0mftq89wpwaymtegmuppyxtfnsp4jcc42cwcz4p6flvd7c5zn4qm3lmtp"
  ],
  "version":"3.0"
}