name: Nix
on:
  push:
    branches:
      - master
      - catalyst-fund*
  pull_request:

jobs:
  build-vitup:
    name: Build vitup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/nix-common-setup
      with:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Flake check
      run: nix flake check --option allow-import-from-derivation true
    - name: Build
      run: nix build .#vitup

  build:
    name: Build ${{ matrix.package }}
    needs: build-vitup
    strategy:
      fail-fast: false
      matrix:
        package:
        - "iapyx"
        - "valgrind"
        - "integration-tests"
        - "registration-service"
        - "registration-verify-service"
        - "snapshot-trigger-service"
        - "signals-handler"
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/nix-common-setup
      with:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Build
      run: nix build .#${{ matrix.package }}
