[package]
name = "registration-service"
version = "0.1.0"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["serde","v4"] }
chrono = { version = "0.4", features = ["serde"] }
walkdir = "2.3.1"
structopt = "0.3"
jortestkit = { git = "https://github.com/input-output-hk/jortestkit.git", branch= "master" }
jormungandr-integration-tests = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
jormungandr-automation = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
jormungandr-lib = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
chain-addr = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-crypto = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
catalyst-toolbox = { git = "https://github.com/input-output-hk/catalyst-toolbox.git", branch = "test_api_for_snapshot", features=["test-api"]}
mainnet-tools = { path = "../mainnet-tools" }
assert_fs = "1.0"
futures = "0.3.8"
libmath = "0.2.1"
serde = { version = "1", features = ["derive"] }
warp = "0.3"
image = "0.23.9"
thiserror = "1.0"
tokio = { version = "1.2", features = ["macros","rt","process"] }
serde_json = "1.0"
serde_yaml = "0.8"
signals-handler = { path = "../signals-handler" }
regex = "1.5.4"

[dependencies.reqwest]
version = "0.10.10"
default-features = false
features = ["blocking", "rustls-tls", "json"]
