[package]
name = "snapshot-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
voting-hir = { git = "https://github.com/input-output-hk/catalyst-toolbox", branch = "catalyst-fund9" }
notify = "=5.0.0-pre.11"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tracing = "0.1.34"
thiserror = "1.0.30"
warp = "0.3.2"
jormungandr-lib = { git = "https://github.com/input-output-hk/jormungandr", branch = "catalyst-fund9" }
sled = "0.34.7"
tokio = "1.18.0"
